generator:
  class: sfHadoriGenerator
  param:
    model_class:           sfGuardUserSubredditMembership
    theme:                   hadori
    non_verbose_templates:   true
    with_show:               true
    singular:                ~
    plural:                  ~
    route_prefix:            subredditmembership
    with_doctrine_route:     true
    i18n:                    false
    sortable:                false
    actions_base_class:      sfActions
    use_security_yaml_credentials: false
    class_label:             Subreddit Membership

    config:
      actions:               ~
      fields:                ~
      list:
        display:             [ sfGuardUser, Subreddit, Membership ]
        sort:                [ membership_id, desc ]
      filter:
        default:
          - display_membership: true
      form:                  ~
      edit:                  ~
      new:                   ~
      show:                  ~
      export:                ~
