generator:
  class:                     sfHadoriGenerator
  param:
    model_class:             AuthorType
    theme:                   hadori
    non_verbose_templates:   true
    with_show:               true
    singular:                ~
    plural:                  ~
    route_prefix:            authortype
    with_doctrine_route:     true
    i18n:                    false
    sortable:                false
    actions_base_class:      sfActions
    use_security_yaml_credentials: false
    class_label:             Author Type

    config:
      actions:               ~
      fields:                ~
      list:
        display:             [ type, description ]
        sort:                [ type, asc ]
      filter:                ~
      form:                  ~
      edit:                  ~
      new:                   ~
      show:                  ~
      export:                ~
