# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - main.css
    - //fonts.googleapis.com/css?family=Arizonia

  javascripts:
    - //ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js
    - //ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js
    - //ajax.googleapis.com/ajax/libs/webfont/1.0.23/webfont.js

  has_layout:     true
  layout:         layout
