<?php

/**
 * ApiKeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApiKeyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApiKeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApiKey');
    }
}