<?php

/**
 * ApplicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplicationTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object ApplicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Application');
    }

    /**
     * Returns whether an Application for a given Subreddit and AuthorType is
     * restricted until the previous AuthorType passes its Deadline.
     *
     * @param int $authortype_id The incremented ID of an AuthorType object
     * @param int $subreddit_id  The incremented ID of a Subreddit object
     * @return bool              Whether the Application record is restricted
     */
    public function getIfApplicationRestrictedByAuthorTypeAndSubreddit($authortype_id,
                                                                       $subreddit_id)
    {
        $application_restricted = $this->createQuery()
                ->select('Application.restricted_until_previous_misses_deadline')
                ->where('Application.author_type_id = ?', $authortype_id)
                ->andWhere('Application.subreddit_id = ?', $subreddit_id)
                ->limit(1)
                ->fetchArray();

        return (count($application_restricted) ? $application_restricted[0]['restricted_until_previous_misses_deadline']
                            : false);
    }

}