<?php

/**
 * AuthFailureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuthFailureTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object AuthFailureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AuthFailure');
    }

    public function countFailuresMadeInRecentSeconds($api_key_id,
                                                     $sf_guard_user_id,
                                                     $seconds = 120)
    {
        $failures = $this->createQuery()
                ->select('COUNT(AuthFailure.id) AS count')
                ->where('AuthFailure.created_at >= ?',
                        date('Y-m-d H:i:s', time() - $seconds))
                ->andWhere('AuthFailure.api_key_id = ?', $api_key_id)
                ->andWhere('AuthFailure.sf_guard_user_id = ?', $sf_guard_user_id)
                ->groupBy('AuthFailure.id')
                ->fetchArray();
        return (count($failures) ? $failures[0]['count'] : 0);
    }

    public function cleanUpOldFailures($seconds = 120)
    {
        $query = $this->createQuery()
                ->delete()
                ->from('AuthFailure')
                ->where('AuthFailure.created_at <= ?',
                        date('Y-m-d H:i:s', time() - $seconds))
                ->execute();
    }

}