<?php

/**
 * DeadlineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeadlineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeadlineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Deadline');
    }
}