<?php

/**
 * Deadline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    OpenMicNight
 * @subpackage model
 * @author     Tom Doggett
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Deadline extends BaseDeadline
{
    /**
     * Returns the Deadline seconds
     *
     * @return string  The object formatted as a string
     */
    public function __toString()
    {
        return (string)$this->getSeconds();
    }
    
    public function setIncremented($id)
    {
        $this->_id = array($id);
        $this->set('id', $id, false);
        $this->_lastModified = array();
    }
}
