<?php

/**
 * DeadlineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeadlineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeadlineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Deadline');
    }
    
    public function getSecondsByAuthorAndSubreddit($author_type_id, $subreddit_id)
    {
        $seconds = $this->createQuery()
                    ->select('Deadline.seconds')
                    ->where('Deadline.author_type_id = ?', $author_type_id)
                    ->andWhere('Deadline.subreddit_id = ?', $subreddit_id)
                    ->execute()
                    ->getFirst();
        return $seconds;
    }
    
    public function getFirstAuthorTypeIdBySubredditWhereDeadlineIsGreaterThan($seconds, $subreddit_id)
    {
        $author_type_id = self::getInstance()->createQuery()
                    ->select('Deadline.author_type_id')
                    ->where('Deadline.subreddit_id = ?', $subreddit_id)
                    ->andWhere('Deadline.seconds > ?', $seconds)
                    ->orderBy('Deadline.seconds ASC')
                    ->fetchOne();
        return $author_type_id;
    }
}