<?php

/**
 * EmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object EmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Email');
    }

    /**
     *
     * @param type $email_type
     * @param type $lang
     * @return type 
     */
    public function getFirstByEmailTypeAndLanguage($email_type, $lang = "en")
    {
        $email_type = EmailTypeTable::getInstance()->findOneByType($email_type);
        if (!$email_type)
            return null;
        $query = $this->createQuery()
                ->where('email_type_id = ?', $email_type->getIncremented())
                ->andWhere('language = ?', $lang)
                ->execute()
                ->getFirst();
        return $query;
    }

}