<?php

/**
 * EpisodeAssignmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EpisodeAssignmentTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object EpisodeAssignmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EpisodeAssignment');
    }

    public function getFirstByUserAuthorTypeAndSubreddit($author_type_id,
                                                          $user_id,
                                                          $subreddit_id)
    {
        $episode_assignments = $this->createQuery()
                ->leftJoin('Episode')
                ->where('EpisodeAssignment.author_type_id = ?',
                        $author_type_id)
                ->andWhere('EpisodeAssignment.sf_guard_user_id = ?',
                           $user_id)
                ->andWhere('Episode.subreddit_id = ?',
                           $subreddit_id)
                ->andWhere('Episode.release_date > NOW()')
                ->execute()
                ->getFirst();
        return $episode_assignments;
    }

}