<?php

/**
 * ProfileSubredditMembershipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileSubredditMembershipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileSubredditMembershipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileSubredditMembership');
    }
}