<?php

/**
 * RedditValidationKeysTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RedditValidationKeysTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RedditValidationKeysTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RedditValidationKeys');
    }
}