<?php

/**
 * sfGuardUserAuthKeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserAuthKeyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserAuthKeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserAuthKey');
    }
}