<?php

/**
 * sfGuardUserAuthKeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserAuthKeyTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserAuthKeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserAuthKey');
    }

    public function getMostRecentValidByApiKeyIdAndAuthKey($api_key_id,
                                                           $auth_key)
    {
        $auth = $this->createQuery()
                ->where('sfGuardUserAuthKey.api_key_id = ?', $api_key_id)
                ->andWhere('sfGuardUserAuthKey.auth_key = ?', $auth_key)
                ->andWhere('sfGuardUserAuthKey.is_revoked = 0')
                ->andWhere('sfGuardUserAuthKey.expires_at >= NOW()')
                ->orderBy('sfGuardUserAuthKey.created_at DESC')
                ->execute()
                ->getFirst();
        return $auth;
    }
}