<?php

/**
 * SubredditTropoNumberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubredditTropoNumberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubredditTropoNumberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubredditTropoNumber');
    }
}