<?php

/**
 * UserSubredditMembershipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserSubredditMembershipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserSubredditMembershipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserSubredditMembership');
    }
}