<?php

/**
 * ValidationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ValidationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ValidationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Validation');
    }
    
    public static function storeNewKeys($values)
    {
        //@todo: The following is MySQL specific!  Not good!
        $sql = 'INSERT IGNORE INTO `validation` (`reddit_key`) VALUES (';
        $first = true;
        foreach($values as $key => $value)
        {
            $sql .= ($first ? '' : '),(') . "'" . $key . "'";
            $first = false;
        }
        $sql .= ');';
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $q->execute($sql);
    }
}