<?php

/**
 * ValidationPostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ValidationPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ValidationPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ValidationPost');
    }
}