message:
  class: sfDoctrineRouteCollection
  options:
    model:                Message
    module:               message
    prefix_path:          /message
    column:               id
    with_wildcard_routes: true

message_send_previous:
  url:  /message/:id/send/:previous
  param: { module: message, action: send}

profile:
  class: sfDoctrineRouteCollection
  options:
    model:                Profile
    module:               profile
    prefix_path:          /profile
    column:               id
    with_wildcard_routes: true

episode:
  class: sfDoctrineRouteCollection
  options:
    model:                Episode
    module:               episode
    prefix_path:          /episode
    column:               id
    with_wildcard_routes: true

feed:
  class: sfDoctrineRouteCollection
  options:
    model:                Feed
    module:               feed
    prefix_path:          /feed
    column:               id
    with_wildcard_routes: true

#feed_index_rss:
#  url:  /feed.rss
#  param: { module: feed, action: index, format: rss }

feed_index_atom:
  url:  /atom.rss
  param: { module: feed, action: index, format: atom }

#feed_user_rss:
#  url:  /user/:reddit_validation_key/feed.rss
#  param: { module: feed, action: user, format: rss }

feed_user_atom:
  url:  /user/:reddit_validation_key/atom.rss
  param: { module: feed, action: user, format: atom }

#feed_subreddit_rss:
#  url:  /r/:domain/feed.rss
#  param: { module: feed, action: subreddit, format: rss }
  
feed_subreddit_atom:
  url:  /r/:domain/atom.rss
  param: { module: feed, action: subreddit, format: atom }

episode_audio:
  url:   /episode/:id/audio.:format
  param: { module: episode, action: audio }

episode_delete:
  url:  /episode/:id/delete
  param: { module: episode, action: delete }

feedback:
  url:  /feedback
  param: { module: home, action: feedback }

feedback_send:
  url:  /send
  param: { module: home, action: send }

feedback_thankyou:
  url:  /thankyou
  param: { module: home, action: thankyou }

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_forgot_password:
  url:   /forgot
  param: { module: sfGuardAuth, action: forgot }

sf_guard_register:
  url:   /register
  param: { module: sfGuardAuth, action: register }

send_to_reddit_post:
  url:   /verify/sendtoreddit
  param: { module: sfGuardAuth, action: validate }

sf_guard_verify:
  url:   /verify/:key
  param: { module: sfGuardAuth, action: verify }
  
about_us:
  url:   /about_us
  param: { module: home, action: aboutus }

api:
  url:   /api
  param: { module: home, action: api }

how_to_help:
  url:   /how_to_help
  param: { module: home, action: howtohelp }

how_to_use:
  url:   /how_to_use
  param: { module: home, action: howtouse }

roadmap:
  url:   /roadmap
  param: { module: home, action: roadmap }

blog:
  url:   /blog
  param: { module: home, action: blog }

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

subreddit_index:
  url:   /r/:domain
  param: { module: subreddit, action: show }

subreddit:
  url:   /r/:domain/:action
  param: { module: subreddit }

subreddit_default:
  url:   /r/:domain/:module/:action/*

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
