# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - main.css
    - http://fonts.googleapis.com/css?family=Arizonia
    - coin-slider-styles.css

  javascripts:
    - https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js
    - http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js
    - http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/additional-methods.min.js
    - https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js
    - https://ajax.googleapis.com/ajax/libs/webfont/1.0.23/webfont.js
    - http://bp.yahooapis.com/2.4.21/browserplus-min.js
    - audio-player.js
    - coin-slider.min.js

  has_layout:     true
  layout:         layout
