generator:
  class:                     sfHadoriGenerator
  param:
    model_class:             Deadline
    theme:                   hadori
    non_verbose_templates:   true
    with_show:               true
    singular:                ~
    plural:                  ~
    route_prefix:            subredditdeadline
    with_doctrine_route:     true
    i18n:                    false
    sortable:                false
    actions_base_class:      sfActions
    use_security_yaml_credentials: false

    config:
      actions:               ~
      fields:
        restricted_until_previous_misses_deadline: { label: Restricted by Previous Deadlines}
      list:
        display:             [ AuthorType, Subreddit, seconds, restricted_until_previous_misses_deadline ]
        sort:                [ subreddit_id, desc, seconds, desc ]
      filter:                ~
      form:                  ~
      edit:                  ~
      new:                   ~
      show:                  ~
      export:                ~
