<?php

/**
 * sfGuardLoginMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardLoginMessageTable extends PluginsfGuardLoginMessageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardLoginMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardLoginMessage');
    }
    
    public function getUndisplayedByUserId($user_id)
    {
        $undisplayed = $this->createQuery()
                ->where('user_id = ?', $user_id)
                ->andWhere('displayed <> 1')
                ->execute();
        return $undisplayed;
    }
}