<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    OpenMicNight
 * @subpackage model
 * @author     Tom Doggett
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
	public function save(Doctrine_Connection $conn = null)
    {
        if (is_null($this->_get('username')) && is_null($this->_get('email_address')))
        {
            //throw new Exception('Cannot save User with null username and email!');
            return;
        }
        parent::save($conn);
    }
}
