<?php

/**
 * sfGuardLoginMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardLoginMessageTable extends PluginsfGuardLoginMessageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardLoginMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardLoginMessage');
    }
}