message:
  class:   sfObjectRouteCollection
  options:
    model:   Message
    actions: [ create, delete, list, show, update ]
    module:  message
    column:  id
    default_params:
      sf_format:  json
subredditmembership:
  class:   sfObjectRouteCollection
  options:
    model:   sfGuardUserSubredditMembership
    actions: [ create, delete, list, show, update ]
    module:  subredditmembership
    column:  id
    default_params:
      sf_format:  json
episodeassignment:
  class:   sfObjectRouteCollection
  options:
    model:   EpisodeAssignment
    actions: [ create, delete, list, show, update ]
    module:  episodeassignment
    column:  id
    default_params:
      sf_format:  json
subredditauthortype:
  class:   sfObjectRouteCollection
  options:
    model:   Application
    actions: [ create, delete, list, show, update ]
    module:  subredditauthortype
    column:  id
    default_params:
      sf_format:  json
subredditdeadline:
  class:   sfObjectRouteCollection
  options:
    model:   Deadline
    actions: [ create, delete, list, show, update ]
    module:  subredditdeadline
    column:  id
    default_params:
      sf_format:  json
subredditauthortypes:
  class:   sfObjectRouteCollection
  options:
    model:   Application
    actions: [ create, delete, list, show, update ]
    module:  subredditauthortypes
    column:  id
    default_params:
      sf_format:  json
user:
  class:   sfObjectRouteCollection
  options:
    model:   sfGuardUser
    actions: [ create, delete, list, show, update ]
    module:  user
    column:  id
    default_params:
      sf_format:  json
request_user_key:
  url:   /user/token
  param: { module: user, action: token }
request_user_id:
  url:   /user_id
  param: { module: user, action: token_user_id }
request_current_time:
  url:   /time
  param: { module: user, action: time }

message:
  class:   sfObjectRouteCollection
  options:
    model:   Message
    actions: [ create, delete, list, show, update ]
    module:  message
    column:  id
    default_params:
      sf_format:  json
membershiptype:
  class:   sfObjectRouteCollection
  options:
    model:   Membership
    actions: [ create, delete, list, show, update ]
    module:  membershiptype
    column:  id
    default_params:
      sf_format:  json
authortype:
  class:   sfObjectRouteCollection
  options:
    model:   AuthorType
    actions: [ create, delete, list, show, update ]
    module:  authortype
    column:  id
    default_params:
      sf_format:  json
episode:
  class:   sfObjectRouteCollection
  options:
    model:   Episode
    actions: [ create, delete, list, show, update ]
    module:  episode
    column:  id
    default_params:
      sf_format:  json
released_episodes:
  url:   /episode/released
  param: { module: episode, action: released }
subreddit:
  class:   sfObjectRouteCollection
  options:
    model:   Subreddit
    actions: [ create, delete, list, show, update ]
    module:  subreddit
    column:  id
    default_params:
      sf_format:  json
# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: doc, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
