<?php

/**
 * PluginsfGuardLoginMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardLoginMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardLoginMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardLoginMessage');
    }
}