Subreddit:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true, unique: true }
    domain: { type: string(127), unique: true }
    is_active: { type: boolean, default: 0 }
    create_new_episodes_cron_formatted: { type: string(32), notnull: true }
    episode_schedule_cron_formatted: { type: string(32), notnull: true }

AuthorType:
  actAs: { Timestampable: ~ }
  options:
    symfony: { filter: false }
  columns:
    type: { type: string(255), notnull: true, unique: true }
    description: { type: string(127) }

RedditValidationKeys:
  options:
    symfony: { filter: false, form: false }
  columns:
    type: { type: string(255), notnull: true }

Membership:
  actAs: { Timestampable: ~ }
  options:
    symfony: { fitler: false }
  columns:
    type: { type: string(255), notnull: true, unique: true }
    description: { type: string(127) }

User:
  actAs: { Timestampable: ~ }
  columns:
    email: { type: string(255), notnull: true, unique: true }
    reddit_validation_key: { type: string(127), notnull: true }
    username: { type: string(255), notnull: true, unique: true }
    salt: { type: string(255) }
    password: { type: string(127), notnull: true }
    full_name: { type: string(127) }
    preferred_name: { type: string(127) }
    website: { type: string(255) }
    twitter_account: { type: string(127) }
    avatar: { type: string(255) }
    short_bio: { type: string(4000) }
    prefer_html: { type: boolean, default: 0 }
    address_line_one: { type: string(127) }
    address_line_two: { type: string(127) }
    city: { type: string(127) }
    state: { type: string(127) }
    zip_code: { type: string(63) }
    country: { type: string(127) }
    display_location: { type: boolean, default: 0 }
    receive_private_messages_from_user_page: { type: boolean, default: 1 }
    receive_notification_of_private_messages: { type: boolean, default: 1 }
    receive_notification_of_newly_opened_episodes: { type: boolean, default: 1 }
    receive_notification_of_episode_approval_pending: { type: boolean, default: 1 }
    last_login: { type: timestamp }
    is_validated: { type: boolean, default: 0 }
    is_active: { type: boolean, default: 0 }
    is_super_admin: { type: boolean, default: 0 }

UserActivationCode:
  actAs: { Timestampable: ~ }
  options:
    symfony: { form: false, filter: false }
  columns:
    user_id: { type: integer, notnull: true }
    code: { type: string(127) }
  relations:
    User: { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: ActivationCodes }

Application:
  actAs: { Timestampable: ~ }
  options: 
    symfony: { filter: false }
  columns:
    author_type_id: { type: integer, notnull: true }
    subreddit_id: { type: integer, notnull: true }
    restricted_until_previous_misses_deadline: { type: boolean, default: 0 }
  relations:
    AuthorType: { onDelete: CASCADE, local: author_type_id, foreign: id, foreignAlias: Applications }
    Subreddit: { onDelete: CASCADE, local: subreddit_id, foreign: id, foreignAlias: Applications }
  indexes:
    oneOfEachAuthorTypePerSubreddit:
      fields: { author_type_id, subreddit_id }
      type: unique

Deadline:
  actAs: { Timestampable: ~ }
  options:
    symfony: { filter: false }
  columns:
    author_type_id: { type: integer, notnull: true }
    subreddit_id: { type: integer, notnull: true }
    seconds: { type: integer, notnull = true }
  relations:
    AuthorType: { onDelete: CASCADE, local: author_type_id, foreign: id, foreignAlias: Deadlines }
    Subreddit: { onDelete: CASCADE, local: subreddit_id, foreign: id, foreignAlias: Deadlines }
  indexes:
    oneOfEachAuthorTypePerSubreddit:
      fields: { author_type_id, subreddit_id }
      type: unique

Message:
  actAs: { Timestampable: ~ }
  options:
    symfony: { filter: false }
  columns:
    recipient_id: { type: integer, notnull: true }
    sender_id: { type: integer }
    previous_message_id: { type: integer, unique: true }
    text: { type: string(4000) }
  relations:
    User: { onDelete: CASCADE, local: recipient_id, foreign: id, foreignAlias: ReceivedMessages }
    User: { onDelete: CASCADE, local: sender_id, foreign: id, foreignAlias: SentMessages }
    Message: { onDelete: SET NULL, local: previous_message_id, foreign: id, foreignAlias: Replies }

UserSubredditMembership:
  actAs: { Timestampable: ~ }
  columns:
    user_id: { type: integer, notnull: true }
    subreddit_id: { type: integer, notnull: true }
    membership_id: { type: integer, notnull: true }
    display_membersship: { type: boolean, default: 0 }
  relations:
    User: { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: SubredditMemberships }
    Subreddit: { onDelete: CASCADE, local: subreddit_id, foreign: id, foreignAlias: UserMemberships }
    Membership: { onDelete: CASCADE, local: membership_id, foreign: id, foreignAlias: SubredditUsers }
  indexes:
    oneUserMembershipPerSubreddit:
      fields: { user_id, subreddit_id }
      type: unique

Episode:
  actAs: { Timestampable: ~ }
  columns:
    user_id: { type: integer, notnull: true }
    subreddit_id: { type: integer, notnull: true }
    approved_by: { type: integer }
    release_date: { type: timestamp, notnull: true }
    audio_file: { type: string(255) }
    nice_filename: { type: string(255) }
    graphic_file: { type: string(255) }
    is_nsfw: { type: boolean, default: 0 }
    title: { type: string(255) }
    description: { type: string(4000) }
    is_submitted: { type: boolean, default: 0 }
    submitted_at: { type: timestamp }
    is_approved: { type: boolean, default: 0 }
    approved_at: { type: timestamp }
    reddit_post_url: { type: string(255) }
  relations:
    User: { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: SubmittedEpisodes }
    User: { onDelete: SET NULL, local: approved_by, foreign: id, foreignAlias: ApprovedEpisodes }
    Subreddit: { onDelete: CASCADE, local: subreddit_id, foreign: id, foreignAlias: Episodes }

EpisodeAssignment:
  actAs: { Timestampable: ~ }
  columns:
    author_type_id: { type: integer, notnull: true }
    user_id: { type: integer, notnull: true }
    episode_id: { type: integer, notnull: true }
    missed_deadline: { type: boolean, default: 0 }
  relations:
    AuthorType: { onDelete: CASCADE, local: author_type_id, foreign: id, foreignAlias: EpisodeAssignments }
    User: { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: EpisodeAssignments }
    Episode: { onDelete: CASCADE, local: episode_id, foreign: id, foreignAlias: EpisodeAssignments }
  indexes:
    noMultipleUserAssignmentsPerEpisode:
      fields: { user_id, episode_id }
      type: unique
    noMultipleAuthorTypeAssignmentsPerEpisode:
      fields: { author_type_id, episode_id }
      type: unique